---
#----------------------------------------------------------------------------
# パッケージをインストールする
#----------------------------------------------------------------------------
- name: install({{ item }})
  apt:
    name:
      - '{{ item }}'
    state: installed
  tags: package
