---
#----------------------------------------------------------------------------
# ロケールを設定する
#----------------------------------------------------------------------------
- include: installPackage.yml
  with_items:
    - ibus-kkc
    - vlgothic-*
  tags: package

- name: check locale
  shell: localectl | grep LANG='{{ lang }}'
  register: result
  changed_when: no
  failed_when: no
  check_mode: no

- block:

  - name: create locale
    shell: localedef -f {{ lang.split('.')[1] }} -i {{ lang.split('.')[0] }} {{ lang }}

  - name: set locale
    shell: localectl set-locale LANG='{{ lang }}'

  - name: set keymap
    shell: localectl set-keymap '{{ keymap }}'

  when: result.rc!=0
