---
#----------------------------------------------------------------------------
# パッケージを更新する
#----------------------------------------------------------------------------
- name: update package
  yum:
    name: '*'
    state: latest
    update_cache: yes
  tags: package
