---
#----------------------------------------------------------------------------
# ファイルをコピーする
#----------------------------------------------------------------------------
- name: copy({{ item.dest }})
  copy:
    src: '{{ item.src }}'
    dest:  '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode:  '{{ item.mode  }}'
    backup: yes
